### ISSUE TITLE
Uncaught Error: QWeb2: Template 'FieldMask' not found

### ISSUE THREAD

**Issue by waleed0001** [gilvanleal/odoowidgets#8]
While Using this widget I got exception

```
http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'FieldMask' not found
    at Object.exception (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:2908:7)
    at Engine._render (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:2953:103)
    at Engine.render (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:2949:151)
    at Class.renderElement (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:3113:1073)
    at Class.renderElement (http://104.197.66.17:8069/web/content/991-d63d440/web.assets_backend.js:2240:2962)
    at Class.prototype.(anonymous function) [as renderElement] (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:3010:559)
    at Class.renderElement (http://104.197.66.17:8069/web/content/991-d63d440/web.assets_backend.js:2246:1462)
    at Class.prototype.(anonymous function) [as renderElement] (http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:3010:559)
    at http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:3113:917
    at http://104.197.66.17:8069/web/content/867-4658c14/web.assets_common.js:547:681
```

**Comment by gilvanleal** [comment]
I could not simulate the reported error.
The widget was only tested in version 10.0
